version: "3"

services:
  captainhooks:
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/captain-hooks
    command: ["npm", "run", "start"]

  telethon:
    build:
      context: ./telethon
